version: '3.9'

services:
  api:
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      DB_USERNAME: postgres
      DB_PASSWORD: password
      DB_HOST: db
      DB_NAME: postgres
      DB_PORT: 5432
      JWT_SECRET: secret

    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres
    volumes:
      - user-data:/var/lib/porgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  user-data: